Development
Greg0109/NewYorkTimesClone pull request #2
Opened 2021-01-13 16:39 UTC by Greg0109

2021-01-13 16:44 UTC, Spayco requested changes
## Invalid 🛑 

I can't review the project at the moment, in order to fix this :
* [x] Pull Request should have a meaningful title and a brief description ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
* [ ] fix all your linter errors ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/linter_config.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/54883773/))


Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

2021-01-13 17:54 UTC, andresporras3423 requested changes
### Status: Changes Required :recycle:
**Hello Greg Rábago Sainz & Ryel Banfield** 
Good job with your first submission for this project :muscle:  :muscle:
There are some details to improve before you can go ahead:

- [ ] Remove horizontal scrollbar
- [ ] Add a screenshot in your README file
- [ ] The NY Times logo, in the navigation bar, is a link
- [ ] A "Log In" button should appear on the rightmost side of the navbar
- [ ] group selectors with the same style definition
- [ ] You didn't include the editor's pick section
 
Please request another review once you are ready! :+1: 
 
Happy coding :relaxed:
 
Oscar Andrés Russi Porras

2021-01-13 17:54 UTC, andresporras3423 commented on style.css
> +}
Group selectors with the same style definition

2021-01-14 10:44 UTC, umairarshadbutt reviewed
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @Greg0109 and @RyelBanfield 
Good job with the changes! :tada: We are almost there.
We, however, do have a few changes to carry out before we proceed (see review comment).

##

Kindly work on the suggested changes  👇.
- [x] Add a description in `alt` attribute
- [x] Add a description in `href` attribute
- [x] MIT Lisence link is not working in the README file
- [x] Add .gitignore file and remove and remove .DS_Store from repo
- [x] Login button is not visible properly in navabr 
![See image](https://user-images.githubusercontent.com/29689273/104580626-4f86c600-567f-11eb-88c7-edab987ceeaa.png)
 
##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

2021-01-14 10:44 UTC, umairarshadbutt commented on index.html
> +                <a href="">
Add a description in `href` attribute

2021-01-14 10:44 UTC, umairarshadbutt commented on index.html
> +            alt=""
Add a description in `alt` attribute

2021-01-14 10:44 UTC, umairarshadbutt commented on index.html
> +            alt=""
Add a description in `alt` attribute

2021-01-14 14:02 UTC, Georjane approved these changes
## Status: PR Approved 💯 🥇
### Hi Team✋🏽
Nice work. Your project meets the minimum requirements for it to be approved. It's a thumbs up for me. 👍🏽 You can go ahead and merge this pull request.🤝

Good luck on your next project and Happy Coding 💻

2021-01-14 14:06 UTC, Greg0109 commented
Thanks!

2021-01-14 14:07 UTC, merged